// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs4pi5uiRfAvJV5g0bSDVIBcQ1tomtyRY',
    appId: '1:489562438342:web:c27988e02d7bd148a7f5c7',
    messagingSenderId: '489562438342',
    projectId: 'mutkal',
    authDomain: 'mutkal.firebaseapp.com',
    databaseURL: 'https://mutkal-default-rtdb.firebaseio.com',
    storageBucket: 'mutkal.appspot.com',
    measurementId: 'G-9M46KYR7YM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSnHBejSGd7jHeSwXH3kfKBaoI16esSOU',
    appId: '1:489562438342:android:0316843f3b584864a7f5c7',
    messagingSenderId: '489562438342',
    projectId: 'mutkal',
    databaseURL: 'https://mutkal-default-rtdb.firebaseio.com',
    storageBucket: 'mutkal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcHfTMMmwBvbgluCP1ClJjQq6Gy0X76sI',
    appId: '1:489562438342:ios:bd11e36da649277aa7f5c7',
    messagingSenderId: '489562438342',
    projectId: 'mutkal',
    databaseURL: 'https://mutkal-default-rtdb.firebaseio.com',
    storageBucket: 'mutkal.appspot.com',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcHfTMMmwBvbgluCP1ClJjQq6Gy0X76sI',
    appId: '1:489562438342:ios:bd11e36da649277aa7f5c7',
    messagingSenderId: '489562438342',
    projectId: 'mutkal',
    databaseURL: 'https://mutkal-default-rtdb.firebaseio.com',
    storageBucket: 'mutkal.appspot.com',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs4pi5uiRfAvJV5g0bSDVIBcQ1tomtyRY',
    appId: '1:489562438342:web:efcca2c293c2275fa7f5c7',
    messagingSenderId: '489562438342',
    projectId: 'mutkal',
    authDomain: 'mutkal.firebaseapp.com',
    databaseURL: 'https://mutkal-default-rtdb.firebaseio.com',
    storageBucket: 'mutkal.appspot.com',
    measurementId: 'G-PZ2P348B46',
  );

}